version: "3"
services: 
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
  client:
    container_name: "client"
    build: 
      context: ./client    
    ports: 
    - "3000"
  api:
    depends_on: 
      - mongo
    container_name: "api"
    build: 
      context: ./server
    ports: 
      - "5000"
  mongo:
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""